# Generated by Django 4.0.6 on 2024-04-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('apresentacao', models.TextField()),
                ('objetivos', models.TextField()),
                ('competencias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=10)),
                ('ects', models.IntegerField()),
                ('curricular_unit_readable_code', models.CharField(max_length=20)),
                ('area_cientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.areacientifica')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LinguagemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('conceitos_aplicados', models.TextField()),
                ('tecnologias_usadas', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('video_demo', models.URLField()),
                ('link_github', models.URLField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.disciplina')),
                ('linguagens_programacao', models.ManyToManyField(to='curso.linguagemprogramacao')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='docentes',
            field=models.ManyToManyField(to='curso.docente'),
        ),
    ]
