# Generated by Django 4.0.6 on 2024-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='semestre',
            field=models.CharField(max_length=25),
        ),
    ]
