# Generated by Django 4.0.6 on 2024-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_disciplina_semestre_alter_projeto_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='area_cientifica',
            field=models.ManyToManyField(to='curso.areacientifica'),
        ),
    ]
