# Generated by Django 4.0.6 on 2024-06-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_curso_area_cientifica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='area_cientifica',
        ),
        migrations.AddField(
            model_name='areacientifica',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_cientificas', to='curso.curso'),
        ),
    ]
