# Generated by Django 4.0.6 on 2024-04-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_album_capa_banda_foto_banda_informacoes_variadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='informacoes_variadas',
        ),
    ]
