# Generated by Django 4.0.6 on 2024-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_remove_banda_foto_remove_banda_informacoes_variadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
