# Generated by Django 4.0.6 on 2024-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_rename_lancamento_album_ano_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='ano_lancamento',
            field=models.CharField(max_length=100),
        ),
    ]
