# Generated by Django 4.0.6 on 2024-04-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_album_banda_musica_delete_pessoa_album_banda'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='ano_criacao',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='ano_lancamento',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='banda',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='musica',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
