# Generated by Django 4.0.6 on 2024-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_banda_ano_criacao_banda_nacionalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='ano_lancamento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='banda',
            name='ano_criacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(max_length=50),
        ),
    ]
