# Generated by Django 4.0.6 on 2024-03-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtigoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('ingredientes', models.TextField()),
                ('tempo_preparo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='receitas/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artigos.autor')),
            ],
        ),
        migrations.CreateModel(
            name='ArtigoAirbnb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='airbnb/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artigos.autor')),
            ],
        ),
    ]
