# Generated by Django 4.0.6 on 2024-05-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtigoAirbnb',
        ),
    ]
